### ISSUE TITLE
padding issue

### ISSUE THREAD

**Issue by mimoo** [mimoo/DES#1]
si la taille du fichier qu'on lit n'est pas un multiple de 64bits ca bug, normal puisqu'il ne sait pas comment crypter/décrypter le dernier block de taille inférieur à 64bits.

Pour cela on pad avec des 000000...

seulement, comment le programme sait-il combien de zéros font parti réellement du fichier à la fin ? Par exemple si notre fichier se termine avec un 0000, puis qu'on pad avec 0000. Le programme peut croire que les 8 derniers zéros sont du padding.

Plus d'infos ici : http://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Padding

> Schneier and Ferguson suggest two possibilities, both simple: append a byte with value 128 (hex 80), followed by as many zero bytes as needed to fill the last block, or pad the last block with n bytes all with value n.

**Comment by mardagbash** [comment]
asdfghj
