### ISSUE TITLE
Bug in DES.c causing incorrect output

### ISSUE THREAD

**Issue by rswjr** [mimoo/DES#6]
In DES.c, line 296:
`coordy += 2^(4 - jj);`

This line seems to try to set the bit at position `(4 - jj)`, but the caret symbol does not perform exponentiation in C.  This is causing the program as written to produce the wrong ciphertext.

**Comment by mimoo** [comment]
good catch :) this is old code though, so I'm not going to fix it unless you want to submit a PR + some test vectors

**Comment by cmcqueen** [comment]
If you're going to share code, it is good to fix known bugs (regardless of whether the code is "old" or not).

**Comment by mimoo** [comment]
added the bug to the README
